### ISSUE TITLE
replace `connect` with `browser-sync`?

### ISSUE THREAD

**Issue by stryju** [zurb/foundation-apps-template#12]
Hey guys!

I'd like to propose a switch from `connect` to [`browser-sync`](http://www.browsersync.io/)
it's super-easily [integrated with gulp](http://www.browsersync.io/docs/gulp/) and is built on top of connect, so middleware will work just fine :-)

WDYT?

**Comment by gakimball** [comment]
Sorry, I know this is an older PR, but we ended up implementing LiveReload: #21
