### ISSUE TITLE
unordered_map::at: key not found on line undefined in undefined

### ISSUE THREAD

**Issue by joebell93** [zurb/foundation-apps-template#24]
When running npm start, I get the following error:

    [gulp-sass] unordered_map::at: key not found on line undefined in undefined

This also prevents any CSS files being created in 'build'.

**Comment by joebell93** [comment]
My temporary solution has been to comment out
```
.pipe($.autoprefixer({
   browsers: ['last 2 versions', 'ie 10']
}))

**Comment by gakimball** [comment]
Ah yeah, there have been issues with Autoprefixer trying to process a CSS sourcemap.

You can get around it by setting up a filter using [gulp-filter](https://www.npmjs.com/package/gulp-filter) that temporarily removes the map files.

```js
var filter = $.filter('*.css');

// ...start of stream
.pipe(filter)
  .pipe($.autoprefixer())
.pipe(filter.restore())
// ...rest of stream
```

**Comment by joebell93** [comment]
Great, thanks!
