### ISSUE TITLE
npm start fails with sass error

### ISSUE THREAD

**Issue by albertgo** [zurb/foundation-apps-template#29]
Hi,

I have this error, anyone can help me?

**[npm-debug.txt](https://github.com/zurb/foundation-apps-template/files/136569/npm-debug.txt)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! foundation-apps-template@1.2.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-apps-template@1.2.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-apps-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-apps-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-apps-template
npm ERR! There is likely additional logging output above.**

**Comment by gakimball** [comment]
Try running Gulp manually and see what happens.

``` bash
npm install gulp --global
gulp
```

You'll probably still get an error—can you post the error you get?

**Comment by albertgo** [comment]
This is the error:

<pre>C:\xampp\htdocs\fornsCuits>gulp
[10:23:34] Using gulpfile C:\xampp\htdocs\fornsCuits\gulpfile.js
[10:23:34] Starting 'build'...
[10:23:34] Starting 'clean'...
[10:23:34] Finished 'clean' after 6.05 ms
[10:23:34] Starting 'copy'...
[10:23:34] Starting 'copy:foundation'...
[10:23:36] Finished 'copy:foundation' after 1.26 s
[10:23:36] Starting 'sass'...
[10:23:38] Starting 'uglify:foundation'...
[10:23:38] Starting 'uglify:app'...
[10:23:38] Finished 'uglify:foundation' after 30 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: client\assets\scss\_settings.scss
Error: File to import not found or unreadable: helpers/functions
       Parent style sheet: C:/xampp/htdocs/fornsCuits/client/assets/scss/_settings.scss
        on line 32 of client/assets/scss/_settings.scss
>> @import "helpers/functions";
   ^
    at options.error (C:\xampp\htdocs\fornsCuits\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:277:32)</pre>

**Comment by LichtAnd** [comment]
Did you install the dependencies?

npm install
bower install

**Comment by albertgo** [comment]
Hi LichtAnd,

I installed the foundation and the dependencies behind a proxy, and bower don't give me any error. 

When I execute the command "bower install" it give me an error found because I have a proxy. I executed without proxy and it works. Thank you!.

**Comment by gakimball** [comment]
Good to hear :) Thank you @LichtAnd!

**Comment by LichtAnd** [comment]
Glad I could help.

**Comment by srisrim** [comment]
Same error I am also facing. Installed all dependencies
